async function N(q){try{console.log("[generator] Starting MHTML generation");let w=await Y(q);console.log("[generator] Collected resources:",w.length);let k=O(q);console.log("[generator] Created header:",k);let G=W(q);console.log("[generator] Main content length:",G.length);let E=w.map(X);console.log("[generator] Resource parts:",E.length);let F=[k,`--REPUBFOX-MHTML-BOUNDARY\r
${G}`,...E.map((J)=>`--REPUBFOX-MHTML-BOUNDARY\r
${J}`),`--REPUBFOX-MHTML-BOUNDARY--\r
`].join(`\r
`);return console.log("[generator] MHTML structure (first 500 chars):",F.substring(0,500)),new TextEncoder().encode(F)}catch(w){throw console.error("[generator] Error generating MHTML:",w),w}}function O(q){let w=q.location.href,k=["From: Saved by RepubFox","Subject: "+q.title,"Date: "+new Date().toUTCString(),"MIME-Version: 1.0",'Content-Type: multipart/related; boundary="REPUBFOX-MHTML-BOUNDARY"',"Snapshot-Content-Location: "+w].join(`\r
`);return console.log("[generator] Header created:",k),k+`\r
\r
`}function V(q){console.log("[generator] Original text sample (first 1000 chars):",q.slice(0,1000));let w=q.replace(/\r\n|\n|\r/g,`\r
`),G=new TextEncoder().encode(w),E=Array.from(G).map((A)=>{if(A>=33&&A<=126&&A!==61||A===32||A===9)return String.fromCharCode(A);else return"="+A.toString(16).toUpperCase().padStart(2,"0")}).join("");return console.log("[generator] Encoded text sample (first 1000 chars):",E.slice(0,1000)),E}function W(q){let w=q.location.href,k=`<meta name="mhtml-location" content="${w}">`,G=`<base href="${w}">`,E=q.documentElement.outerHTML;if(!E.includes("<head"))E=E.replace("<html","<html><head></head>");E=E.replace(/<head[^>]*>/,`$&${k}${G}`),E=`<!DOCTYPE html>
${E}`;let A=V(E),F=["Content-Type: text/html","Content-Transfer-Encoding: quoted-printable","Content-Location: "+w,"",A].join(`\r
`);return console.log("[generator] Main content created with Content-Type: text/html"),console.log("[generator] Content length:",A.length),F}function X(q){let k=[`Content-Type: ${q.contentType.includes("charset=")?q.contentType:`${q.contentType}; charset=utf-8`}`,"Content-Transfer-Encoding: base64","Content-Location: "+q.url,"",q.content].join(`\r
`);return console.log("[generator] Resource part created for:",q.url),k}async function Y(q){let w=[],k=new Set,G=q.getElementsByTagName("img");for(let A of G){let F=A.src;if(F&&!F.startsWith("data:")&&!k.has(F))try{let J=await(await fetch(F)).blob(),K=(await Z(J)).split(",")[1];if(K)w.push({url:F,content:K,contentType:J.type||"application/octet-stream"}),k.add(F)}catch(I){console.warn(`Failed to fetch image: ${F}`,I)}}let E=q.styleSheets;for(let A of E)if(A.href&&!k.has(A.href))try{let I=await(await fetch(A.href)).text();w.push({url:A.href,content:btoa(I),contentType:"text/css"}),k.add(A.href)}catch(F){console.warn(`Failed to fetch stylesheet: ${A.href}`,F)}return w}function Z(q){return new Promise((w,k)=>{let G=new FileReader;G.onloadend=()=>w(G.result),G.onerror=k,G.readAsDataURL(q)})}console.log("[content] Content script loaded");browser.runtime.onMessage.addListener((q,w)=>{if(console.log("[content] Received message",{type:q.type,sender:w}),q.type==="capture-mhtml")try{return console.log("[content] Starting MHTML capture..."),console.log("[content] Document title:",document.title),console.log("[content] Document URL:",document.location.href),console.log("[content] Document has images:",document.getElementsByTagName("img").length),console.log("[content] Document has stylesheets:",document.styleSheets.length),N(document).then((k)=>{return console.log("[content] MHTML capture completed, size:",k.byteLength),{success:!0,data:k}}).catch((k)=>{return console.error("[content] MHTML capture failed:",k),{success:!1,error:k instanceof Error?k.message:String(k)}})}catch(k){return console.error("[content] MHTML capture failed (sync):",k),Promise.resolve({success:!1,error:k instanceof Error?k.message:String(k)})}return console.log("[content] Unhandled message type:",q.type),Promise.resolve(void 0)});
