async function A(f){try{console.log("[generator] Starting MHTML generation");let D=await j(f);console.log("[generator] Collected resources:",D.length);let O=$(f);console.log("[generator] Created header:",O);let F=Q(f);console.log("[generator] Main content length:",F.length);let k=D.map(S);console.log("[generator] Resource parts:",k.length);let J=[O,`--REPUBFOX-MHTML-BOUNDARY\r
${F}`,...k.map((Z)=>`--REPUBFOX-MHTML-BOUNDARY\r
${Z}`),`--REPUBFOX-MHTML-BOUNDARY--\r
`].join(`\r
`);return console.log("[generator] MHTML structure (first 500 chars):",J.substring(0,500)),new TextEncoder().encode(J)}catch(D){throw console.error("[generator] Error generating MHTML:",D),D}}function $(f){let D=f.location.href,O=["From: Saved by RepubFox","Subject: "+f.title,"Date: "+new Date().toUTCString(),"MIME-Version: 1.0",'Content-Type: multipart/related; boundary="REPUBFOX-MHTML-BOUNDARY"',"Snapshot-Content-Location: "+D].join(`\r
`);return console.log("[generator] Header created:",O),O+`\r
\r
`}function z(f){console.log("[generator] Original text sample (first 1000 chars):",f.slice(0,1000));let D=f.replace(/\r\n|\n|\r/g,`\r
`),F=new TextEncoder().encode(D),k="";for(let K=0;K<F.length;K++){let Y=F[K];if(Y===void 0)continue;if(Y>=33&&Y<=126&&Y!==61||Y===32&&K+1<F.length&&F[K+1]!==13&&F[K+1]!==10||Y===9&&K+1<F.length&&F[K+1]!==13&&F[K+1]!==10)k+=String.fromCharCode(Y);else k+="="+Y.toString(16).toUpperCase().padStart(2,"0")}let W=76,J=[],V="";for(let K=0;K<k.length;){if(k[K]==="="&&K+2<k.length){let Y=k.slice(K,K+3);if(V.length>=W-Y.length){J.push(V+"="),V="";continue}V+=Y,K+=3;continue}if(V.length>=W-1){J.push(V+"="),V="";continue}V+=k[K],K++}if(V)J.push(V);let Z=J.join(`\r
`);return console.log("[generator] Encoded text sample (first 1000 chars):",Z.slice(0,1000)),Z}function Q(f){let D=f.location.href,O=`<meta name="mhtml-location" content="${D}">`,F=`<base href="${D}">`,k=f.documentElement.outerHTML;if(!k.includes("<head"))k=k.replace("<html","<html><head></head>");k=k.replace(/<head[^>]*>/,`$&${O}${F}`),k=`<!DOCTYPE html>
${k}`;let W=z(k),J=["Content-Type: text/html; charset=UTF-8","Content-Transfer-Encoding: quoted-printable","Content-Location: "+D,"",W].join(`\r
`);return console.log("[generator] Main content created with Content-Type: text/html"),console.log("[generator] Content length:",W.length),J}function S(f){let O=[`Content-Type: ${f.contentType.includes("charset=")?f.contentType:`${f.contentType}; charset=utf-8`}`,"Content-Transfer-Encoding: base64","Content-Location: "+f.url,"",f.content].join(`\r
`);return console.log("[generator] Resource part created for:",f.url),O}async function j(f){let D=[],O=new Set,F=f.getElementsByTagName("img");for(let W of F){let J=W.src;if(J&&!J.startsWith("data:")&&!O.has(J))try{let Z=await(await fetch(J)).blob(),Y=(await q(Z)).split(",")[1];if(Y)D.push({url:J,content:Y,contentType:Z.type||"application/octet-stream"}),O.add(J)}catch(V){console.warn(`Failed to fetch image: ${J}`,V)}}let k=f.styleSheets;for(let W of k)if(W.href&&!O.has(W.href))try{let V=await(await fetch(W.href)).text();D.push({url:W.href,content:btoa(V),contentType:"text/css"}),O.add(W.href)}catch(J){console.warn(`Failed to fetch stylesheet: ${W.href}`,J)}return D}function q(f){return new Promise((D,O)=>{let F=new FileReader;F.onloadend=()=>D(F.result),F.onerror=O,F.readAsDataURL(f)})}export{A as generateMHTML};
