async function Y(f){try{console.log("[generator] Starting MHTML generation");let k=await V(f);console.log("[generator] Collected resources:",k.length);let w=J(f);console.log("[generator] Created header:",w);let E=N(f);console.log("[generator] Main content length:",E.length);let A=k.map(O);console.log("[generator] Resource parts:",A.length);let D=[w,`--REPUBFOX-MHTML-BOUNDARY\r
${E}`,...A.map((G)=>`--REPUBFOX-MHTML-BOUNDARY\r
${G}`),`--REPUBFOX-MHTML-BOUNDARY--\r
`].join(`\r
`);return console.log("[generator] MHTML structure (first 500 chars):",D.substring(0,500)),new TextEncoder().encode(D)}catch(k){throw console.error("[generator] Error generating MHTML:",k),k}}function J(f){let k=f.location.href,w=["From: Saved by RepubFox","Subject: "+f.title,"Date: "+new Date().toUTCString(),"MIME-Version: 1.0",'Content-Type: multipart/related; boundary="REPUBFOX-MHTML-BOUNDARY"',"Snapshot-Content-Location: "+k].join(`\r
`);return console.log("[generator] Header created:",w),w+`\r
\r
`}function K(f){console.log("[generator] Original text sample (first 1000 chars):",f.slice(0,1000));let k=f.replace(/\r\n|\n|\r/g,`\r
`),E=new TextEncoder().encode(k),A=Array.from(E).map((q)=>{if(q>=33&&q<=126&&q!==61||q===32||q===9)return String.fromCharCode(q);else return"="+q.toString(16).toUpperCase().padStart(2,"0")}).join("");return console.log("[generator] Encoded text sample (first 1000 chars):",A.slice(0,1000)),A}function N(f){let k=f.location.href,w=`<meta name="mhtml-location" content="${k}">`,E=`<base href="${k}">`,A=f.documentElement.outerHTML;if(!A.includes("<head"))A=A.replace("<html","<html><head></head>");A=A.replace(/<head[^>]*>/,`$&${w}${E}`),A=`<!DOCTYPE html>
${A}`;let q=K(A),D=["Content-Type: text/html","Content-Transfer-Encoding: quoted-printable","Content-Location: "+k,"",q].join(`\r
`);return console.log("[generator] Main content created with Content-Type: text/html"),console.log("[generator] Content length:",q.length),D}function O(f){let w=[`Content-Type: ${f.contentType.includes("charset=")?f.contentType:`${f.contentType}; charset=utf-8`}`,"Content-Transfer-Encoding: base64","Content-Location: "+f.url,"",f.content].join(`\r
`);return console.log("[generator] Resource part created for:",f.url),w}async function V(f){let k=[],w=new Set,E=f.getElementsByTagName("img");for(let q of E){let D=q.src;if(D&&!D.startsWith("data:")&&!w.has(D))try{let G=await(await fetch(D)).blob(),I=(await W(G)).split(",")[1];if(I)k.push({url:D,content:I,contentType:G.type||"application/octet-stream"}),w.add(D)}catch(F){console.warn(`Failed to fetch image: ${D}`,F)}}let A=f.styleSheets;for(let q of A)if(q.href&&!w.has(q.href))try{let F=await(await fetch(q.href)).text();k.push({url:q.href,content:btoa(F),contentType:"text/css"}),w.add(q.href)}catch(D){console.warn(`Failed to fetch stylesheet: ${q.href}`,D)}return k}function W(f){return new Promise((k,w)=>{let E=new FileReader;E.onloadend=()=>k(E.result),E.onerror=w,E.readAsDataURL(f)})}export{Y as generateMHTML};
